name: offtarget_env_internal
channels:
  - anaconda 
  - knime
  - conda-forge
dependencies:
  - python=3.9              # base dependency
  - knime-python-base>=4.6  # base dependency
  - knime-extension>=4.6    # base dependency
  - keras 
  - h5py
  - tensorflow-base=2.10
  - py4j
  - pandas




